COCOW-TRAIN:
  TYPE: ImageDataset
  URLS: hamer_training_data/dataset_tars/cocow-train/{000000..000036}.tar
  epoch_size: 78666
DEX-TRAIN:
  TYPE: ImageDataset
  URLS: hamer_training_data/dataset_tars/dex-train/{000000..000406}.tar
  epoch_size: 406888
FREIHAND-MOCAP:
  DATASET_FILE: hamer_training_data/freihand_mocap.npz
FREIHAND-TRAIN:
  TYPE: ImageDataset
  URLS: hamer_training_data/dataset_tars/freihand-train/{000000..000130}.tar
  epoch_size: 130240
H2O3D-TRAIN:
  TYPE: ImageDataset
  URLS: hamer_training_data/dataset_tars/h2o3d-train/{000000..000060}.tar
  epoch_size: 121996
HALPE-TRAIN:
  TYPE: ImageDataset
  URLS: hamer_training_data/dataset_tars/halpe-train/{000000..000022}.tar
  epoch_size: 34289
HO3D-TRAIN:
  TYPE: ImageDataset
  URLS: hamer_training_data/dataset_tars/ho3d-train/{000000..000083}.tar
  epoch_size: 83325
INTERHAND26M-TRAIN:
  TYPE: ImageDataset
  URLS: hamer_training_data/dataset_tars/interhand26m-train/{000000..001056}.tar
  epoch_size: 1424632
MPIINZSL-TRAIN:
  TYPE: ImageDataset
  URLS: hamer_training_data/dataset_tars/mpiinzsl-train/{000000..000015}.tar
  epoch_size: 15184
MTC-TRAIN:
  TYPE: ImageDataset
  URLS: hamer_training_data/dataset_tars/mtc-train/{000000..000306}.tar
  epoch_size: 363947
RHD-TRAIN:
  TYPE: ImageDataset
  URLS: hamer_training_data/dataset_tars/rhd-train/{000000..000041}.tar
  epoch_size: 61705
