task_name: train
tags:
- dev
train: true
test: false
ckpt_path: null
seed: null
DATASETS:
  TRAIN:
    FREIHAND-TRAIN:
      WEIGHT: 0.25
    INTERHAND26M-TRAIN:
      WEIGHT: 0.25
    MTC-TRAIN:
      WEIGHT: 0.1
    RHD-TRAIN:
      WEIGHT: 0.05
    COCOW-TRAIN:
      WEIGHT: 0.1
    HALPE-TRAIN:
      WEIGHT: 0.05
    MPIINZSL-TRAIN:
      WEIGHT: 0.05
    HO3D-TRAIN:
      WEIGHT: 0.05
    H2O3D-TRAIN:
      WEIGHT: 0.05
    DEX-TRAIN:
      WEIGHT: 0.05
  VAL:
    FREIHAND-TRAIN:
      WEIGHT: 1.0
  MOCAP: FREIHAND-MOCAP
  BETAS_REG: true
  CONFIG:
    SCALE_FACTOR: 0.3
    ROT_FACTOR: 30
    TRANS_FACTOR: 0.02
    COLOR_SCALE: 0.2
    ROT_AUG_RATE: 0.6
    TRANS_AUG_RATE: 0.5
    DO_FLIP: false
    FLIP_AUG_RATE: 0.0
    EXTREME_CROP_AUG_RATE: 0.0
    EXTREME_CROP_AUG_LEVEL: 1
extras:
  ignore_warnings: false
  enforce_tags: true
  print_config: true
exp_name: hamer
MANO:
  DATA_DIR: _DATA/data/
  MODEL_PATH: data/mano
  GENDER: neutral
  NUM_HAND_JOINTS: 15
  MEAN_PARAMS: data/mano_mean_params.npz
  CREATE_BODY_POSE: false
EXTRA:
  FOCAL_LENGTH: 5000
  NUM_LOG_IMAGES: 4
  NUM_LOG_SAMPLES_PER_IMAGE: 8
  PELVIS_IND: 0
GENERAL:
  TOTAL_STEPS: 1000000
  LOG_STEPS: 1000
  VAL_STEPS: 1000
  CHECKPOINT_STEPS: 10000
  CHECKPOINT_SAVE_TOP_K: 1
  NUM_WORKERS: 8
  PREFETCH_FACTOR: 2
TRAIN:
  LR: 1.0e-05
  WEIGHT_DECAY: 0.0001
  BATCH_SIZE: 32
  LOSS_REDUCTION: mean
  NUM_TRAIN_SAMPLES: 2
  NUM_TEST_SAMPLES: 64
  POSE_2D_NOISE_RATIO: 0.01
  SMPL_PARAM_NOISE_RATIO: 0.005
MODEL:
  IMAGE_SIZE: 256
  IMAGE_MEAN:
  - 0.485
  - 0.456
  - 0.406
  IMAGE_STD:
  - 0.229
  - 0.224
  - 0.225
  BACKBONE:
    TYPE: vit
    PRETRAINED_WEIGHTS: hamer_training_data/vitpose_backbone.pth
  MANO_HEAD:
    TYPE: transformer_decoder
    IN_CHANNELS: 2048
    TRANSFORMER_DECODER:
      depth: 6
      heads: 8
      mlp_dim: 1024
      dim_head: 64
      dropout: 0.0
      emb_dropout: 0.0
      norm: layer
      context_dim: 1280
LOSS_WEIGHTS:
  KEYPOINTS_3D: 0.05
  KEYPOINTS_2D: 0.01
  GLOBAL_ORIENT: 0.001
  HAND_POSE: 0.001
  BETAS: 0.0005
  ADVERSARIAL: 0.0005
